platform :ios, '10.0'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Focus booster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Focus booster
  pod 'Charts'
  pod 'JOCircularSlider'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  target 'Focus boosterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Focus boosterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
